spring:
  datasource:
    url: jdbc:postgresql://docai-db.c4jskea402jt.us-east-1.rds.amazonaws.com:5432/docai
    username: adminuser
    password: DocAI#2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  region: us-east-1
  s3:
    bucket: docai-documents-307946677769
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/307946677769/docai-processing-queue
  bedrock:
    model-id: anthropic.claude-3-haiku-20240307-v1:0

server:
  port: 8080

logging:
  level:
    "[com.docai]": DEBUG
    "[software.amazon.awssdk]": WARN